services:
  postgres:
    image: postgres:16
    container_name: class-db
    environment:
      POSTGRES_DB: classdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - classnet

  rabbitmq:
    image: rabbitmq:3-management
    container_name: class-rabbit
    ports:
      - "5672:5672"
      - "15672:15672" # painel de administração
    networks:
      - classnet

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      # --- CONFIGURAÇÃO DO BANCO DE DADOS POSTGRES ---
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/classdb # Usa o nome do serviço 'postgres'
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: pass
      # --- CONFIGURAÇÃO DE HOSTNAME ---
      KC_HOSTNAME_URL: "http://host.docker.internal:8080"
      KC_HOSTNAME_ADMIN_URL: "http://host.docker.internal:8080"
      KC_PROXY: "edge"
      KC_HTTP_RELATIVE_PATH: /
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_SPI_HOSTNAME_DEFAULT_PROVIDER: "request"
    command:
      - start # Usa o comando 'start' para rodar com banco de dados externo
    restart: unless-stopped
    depends_on:
      - postgres # Garante que o Postgres inicie antes
    networks:
      - classnet
    volumes:
      - keycloak_data:/opt/keycloak/data

  class-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: class-service
    depends_on:
      - postgres
      - rabbitmq
      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/classdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      # Keycloak App Config (Confirmado que é o correto para a comunicação interna)
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: http://host.docker.internal:8080/realms/ifrn
    ports:
      - "8081:8081"
    networks:
      - classnet
    volumes:
      - ~/.m2:/root/.m2

networks:
  classnet:
    driver: bridge

volumes:
  pgdata:
  keycloak_data:
