services:
  postgres:
    image: postgres:16
    container_name: class-db
    environment:
      POSTGRES_DB: classdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - classnet

  class-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: class-service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/classdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass

      KEYCLOAK_SERVER_URL: "http://keycloak:8080"
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KEYCLOAK_REALM: ifrn

      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: admin
      RABBITMQ_PASSWORD: admin123

      MINIO_SERVER_URL: "http://minio:9000"
      MINIO_ADMIN_USER: admin
      MINIO_ADMIN_PASSWORD: admin123
      BUCKET_FILES_NAME: files
      BUCKET_IMAGES_NAME: images

      # Keycloak App Config (Confirmado que é o correto para a comunicação interna)
      #SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: http://host.docker.internal:8080/realms/ifrn
    ports:
      - "8082:8082"
    networks:
      - classnet
      - infra
    volumes:
      - ~/.m2:/root/.m2

networks:
  classnet:
    driver: bridge
  infra:
    external: true

volumes:
  pgdata:
