services:
  import-and-report-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: import-and-report-service
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      KEYCLOAK_SERVER_URL: ${KEYCLOAK_SERVER_URL}
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL}
      MINIO_ADMIN_USER: ${MINIO_ROOT_USER}
      MINIO_ADMIN_PASSWORD: ${MINIO_ROOT_PASSWORD}
      BUCKET_FILES_NAME: ${BUCKET_FILES_NAME}
      BUCKET_IMAGES_NAME: ${BUCKET_IMAGES_NAME}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      SPRING_SERVER_URL: ${SPRING_SERVER_URL}
      SPRING_EXTERNAL_PORT: ${SPRING_EXTERNAL_PORT}
    ports:
      - "8082:8082"
    volumes:
      - ~/.m2:/root/.m2
volumes:
  pgdata:
