services:
  postgres:
    image: postgres:16
    container_name: class-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - classnet

  class-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: class-service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_RABBITMQ_HOST: ${RABBITMQ_HOST}
      SPRING_RABBITMQ_PORT: ${RABBITMQ_PORT}
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      # Keycloak App Config (Confirmado que é o correto para a comunicação interna)
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: http://${OAUTH2_JWT_HOST}:${OAUTH2_JWT_PORT}/realms/ifrn
    ports:
      - "8081:8081"
    networks:
      - classnet
    volumes:
      - ~/.m2:/root/.m2

networks:
  classnet:
    driver: bridge

volumes:
  pgdata:
  keycloak_data:
