services:
  postgres:
    image: postgres:16
    container_name: class-db
    environment:
      POSTGRES_DB: classdb
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - classnet

  import-and-report-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: import-and-report-service
    depends_on:
      academic-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      KEYCLOAK_SERVER_URL: ${KEYCLOAK_SERVER_URL}
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL}
      MINIO_ADMIN_USER: ${MINIO_ROOT_USER}
      MINIO_ADMIN_PASSWORD: ${MINIO_ROOT_PASSWORD}
      BUCKET_FILES_NAME: ${BUCKET_FILES_NAME}
      BUCKET_IMAGES_NAME: ${BUCKET_IMAGES_NAME}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
    ports:
      - "8082:8082"
    networks:
      - academic-network
      - infra
    volumes:
      - ~/.m2:/root/.m2

networks:
  classnet:
    driver: bridge
  infra:
    external: true

volumes:
  pgdata:
