services:
  postgres:
    image: postgres:16
    container_name: class-db
    environment:
      POSTGRES_DB: classdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - classnet

  rabbitmq:
    image: rabbitmq:3-management
    container_name: class-rabbit
    ports:
      - "5672:5672"
      - "15672:15672" # painel de administração
    networks:
      - classnet

  class-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: class-service
    depends_on:
      - postgres
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/classdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    ports:
      - "8081:8081"
    networks:
      - classnet

networks:
  classnet:
    driver: bridge

volumes:
  pgdata:
