server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: ImportReportService

  config:
    import: "optional:dotenv:.env"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: academic-service-backend
            client-secret: NhZI2ZqkycyHPofxWaNNG9bxR1OGCdk8
            authorization-grant-type: authorization_code

            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, email
        provider:
          keycloak:
            user-name-attribute: preferred_username
            # URL que o NAVEGADOR vai usar (fora do docker)
            authorization-uri: http://localhost:8080/realms/ifrn/protocol/openid-connect/auth
            # URL que o BACKEND vai usar (dentro do docker)
            token-uri: http://keycloak:8080/realms/ifrn/protocol/openid-connect/token
            jwk-set-uri: http://keycloak:8080/realms/ifrn/protocol/openid-connect/certs

            #user-info-uri: http://keycloak:8080/realms/ifrn/protocol/openid-connect/userinfo
            #issuer-uri: http://keycloak:8080/realms/ifrn
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/ifrn/protocol/openid-connect/certs

          #issuer-uri: http://keycloak:8080/realms/ifrn



  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

# Configuração do Swagger/OpenAPI
springdoc:
  swagger-ui:
    path: /api/docs
    url: /v3/api-docs
    server-url: http://localhost:8082
    config-url: /v3/api-docs/swagger-config
    oauth:
      client-id: swagger-ui
      use-pkce-with-authorization-code-grant: true
      scopes: openid profile email
      authorization-url: http://localhost:8080/realms/ifrn/protocol/openid-connect/auth
      token-url: http://localhost:8080/realms/ifrn/protocol/openid-connect/token
  show-actuator: true

# Configuração global de CORS (opcional, mas útil no Swagger)
cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      show-details: always


minio:
  server-url: ${MINIO_SERVER_URL}
  admin-user: ${MINIO_ADMIN_USER}
  admin-password: ${MINIO_ADMIN_PASSWORD}
  bucket-files: ${BUCKET_FILES_NAME}
  bucket-images: ${BUCKET_IMAGES_NAME}

keycloak:
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  server-url: ${KEYCLOAK_SERVER_URL}
  admin-user: ${KEYCLOAK_ADMIN_USER}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD}
  realm: ${KEYCLOAK_REALM}